# -*- coding: utf-8 -*-
"""Object detection with YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oO4gZsVt4Vcv1AGvao_Rz3J0cOrRJXKs

# Computer Vision Masterclass - Object detection with YOLO

## Object detection in images

### Downloading Darknet
"""

!git clone https://github.com/AlexeyAB/darknet

ls

cd darknet/

ls

"""### Compiling the library"""

!make

"""### Downloading YOLO weights"""

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

# https://storage.googleapis.com/openimages/web/index.html
# !wget https://pjreddie.com/media/files/yolov3-openimages.weights

"""### Testing the object detector"""

ls

!./darknet detect cfg/yolov4.cfg yolov4.weights data/person.jpg

import cv2
import matplotlib.pyplot as plt
def show_detection(path):
  image = cv2.imread(path)
  fig = plt.gcf()
  fig.set_size_inches(18,10)
  plt.axis('off')
  plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

show_detection('predictions.jpg')

"""### Darknet and GPU"""

import tensorflow as tf
tf.test.gpu_device_name()

ls

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile

!make

!./darknet detect cfg/yolov4.cfg yolov4.weights data/giraffe.jpg

# Coco dataset: https://cocodataset.org/#home
show_detection('predictions.jpg')

"""### Threshold"""

!./darknet detect cfg/yolov4.cfg yolov4.weights data/horses.jpg

show_detection('predictions.jpg')

!./darknet detect cfg/yolov4.cfg yolov4.weights data/horses.jpg -thresh 0.9

show_detection('predictions.jpg')

!./darknet detect cfg/yolov4.cfg yolov4.weights data/horses.jpg -thresh 0.98

show_detection('predictions.jpg')

!./darknet detect cfg/yolov4.cfg yolov4.weights data/horses.jpg -thresh 0.00001

show_detection('predictions.jpg')

"""### ext_output"""

!./darknet detect cfg/yolov4.cfg yolov4.weights data/horses.jpg -ext_output

show_detection('predictions.jpg')

"""## Object detection in videos"""

from google.colab import drive
drive.mount('/content/drive')

ls

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show /content/drive/MyDrive/Cursos\ -\ recursos/Computer\ Vision\ Masterclass/Videos/video_street.mp4 -i 0 -out_filename /content/drive/MyDrive/Cursos\ -\ recursos/Computer\ Vision\ Masterclass/Videos/video_street_result.avi

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show /content/drive/MyDrive/Cursos\ -\ recursos/Computer\ Vision\ Masterclass/Videos/video_people.mp4 -i 0 -out_filename /content/drive/MyDrive/Cursos\ -\ recursos/Computer\ Vision\ Masterclass/Videos/video_people_result.avi